### ISSUE TITLE
Message send failures on some UI actions

### ISSUE THREAD

**Issue by zot** [ccrraaiigg/caffeine#36]
Certain methods are failing for some UI actions, like "create new change set", "simple change sorter" and clicking "save" for appearance settings.

> some of the methods supporting "create new change set" and "simple change sorter" were shaken out when they shouldn't have been. I haven't yet made sure that everything reachable by a human from the world menu is kept from being shaken out. This is effectively fallout from the UI system's use of >>perform:

**Comment by ccrraaiigg** [comment]
This was happening in a version of the object memory that had all unused methods removed. The unit tests that ran before this point didn't touch the behavior you wanted. I've switched back to an unshaken memory for development, so all that stuff should work again.
